# Generated by Django 5.0.4 on 2025-10-05 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0002_remove_employeeprofile_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='company.benefit'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.department'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.position'),
        ),
    ]
