# Generated by Django 5.0.4 on 2025-10-05 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0005_remove_employeeprofile_benefits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='company.benefit'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='date_of_joining',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.department'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.position'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
