# Generated by Django 5.0.4 on 2025-10-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
