# Generated by Django 5.0.4 on 2025-10-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_employeeprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
