# Generated by Django 5.0.4 on 2025-10-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_employeeprofile_name_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=12, max_length=500),
            preserve_default=False,
        ),
    ]
