# Generated by Django 5.0.4 on 2025-10-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
