# Generated by Django 5.0.4 on 2025-10-05 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_initial'),
        ('users', '0007_alter_employeeprofile_salary_payroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='employee',
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('pending_tasks', models.PositiveIntegerField(default=0)),
                ('overdue_tasks', models.PositiveIntegerField(default=0)),
                ('performance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='users.employeeprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='PerformanceEvaluation',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
