# Generated by Django 5.0.4 on 2025-10-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_rename_title_ticket_subject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketAssignment',
        ),
    ]
