# Generated by Django 5.0.4 on 2025-10-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_ticketassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketAssignment',
        ),
    ]
