# Generated by Django 5.0.4 on 2025-10-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketresponse',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
