# Generated by Django 5.0.4 on 2025-10-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_ticketresponse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='Output',
            field=models.BooleanField(default=False),
        ),
    ]
