# Generated by Django 5.0.4 on 2025-10-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_ticketattachment_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Finishing', 'Finishing'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
