# Generated by Django 5.0.4 on 2025-10-09 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_delete_ticketassignment'),
        ('tasks', '0006_task_parent_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='customers.ticket'),
        ),
    ]
