# Generated by Django 5.0.4 on 2025-10-10 12:04

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=tasks.models.default_deadline, null=True),
        ),
    ]
