# Generated by Django 5.0.4 on 2025-10-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_status_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='OutPut',
            field=models.BooleanField(default=False),
        ),
    ]
