# Generated by Django 5.0.4 on 2025-10-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_taskattachment_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskattachment',
            old_name='OutPut',
            new_name='Output',
        ),
    ]
