# Generated by Django 5.0.4 on 2025-10-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_rename_output_taskattachment_output'),
        ('users', '0012_employeeprofile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_employees',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_employees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_tasks', to='users.employeeprofile'),
        ),
    ]
