# Generated by Django 5.0.4 on 2025-10-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_task_assigned_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_employees',
        ),
    ]
